CREATE TABLE IF NOT EXISTS tasks (
    id SERIAL PRIMARY KEY,
    query TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'created',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    depth_level INT NOT NULL DEFAULT 1,
    min_weight FLOAT NOT NULL DEFAULT 0.0
)